const houseServices = [
/*   { title: "Plumbing Repair", startingPrice: 50 },
  { title: "Ceiling Fan Installation", startingPrice: 40 },
  { title: "TV Wall Mounting", startingPrice: 60 },
  { title: "Air Conditioner Service", startingPrice: 80 },
  { title: "Water Tank Cleaning", startingPrice: 70 },
  { title: "Furniture Assembly", startingPrice: 45 },
  { title: "House Deep Cleaning", startingPrice: 120 },
  { title: "Electrical Wiring", startingPrice: 65 },
  { title: "Chimney Cleaning", startingPrice: 55 },
  { title: "Bathroom Fitting", startingPrice: 90 },
  { title: "Pest Control", startingPrice: 75 },
  { title: "RO/Water Purifier Installation", startingPrice: 50 },
  { title: "Carpentry Services", startingPrice: 60 },
  { title: "Geyser Installation", startingPrice: 45 },
  { title: "AC Gas Refilling", startingPrice: 100 },
  { title: "Door Lock Replacement", startingPrice: 30 },
  { title: "LED Light Installation", startingPrice: 25 },
  { title: "Microwave Repair", startingPrice: 70 },
  { title: "Washing Machine Repair", startingPrice: 85 },
  { title: "Kitchen Chimney Repair", startingPrice: 90 },
  { title: "CCTV Camera Installation", startingPrice: 150 },
  { title: "Sofa Cleaning", startingPrice: 60 },
  { title: "Water Leakage Fix", startingPrice: 55 },
  { title: "Curtain Rod Mounting", startingPrice: 35 },
  { title: "Wall Painting", startingPrice: 200 },
  { title: "Tile Fixing", startingPrice: 110 },
  { title: "False Ceiling Work", startingPrice: 300 },
  { title: "Modular Kitchen Setup", startingPrice: 500 },
  { title: "Glass Partition Work", startingPrice: 250 },
  { title: "Floor Polishing", startingPrice: 180 },
  { title: "Wall Drilling", startingPrice: 25 },
  { title: "Bathroom Waterproofing", startingPrice: 120 },
  { title: "Garage Door Repair", startingPrice: 100 },
  { title: "Window Mesh Installation", startingPrice: 45 },
  { title: "Roof Leak Fix", startingPrice: 130 },
  { title: "Inverter Installation", startingPrice: 80 },
  { title: "Solar Panel Setup", startingPrice: 700 },
  { title: "Septic Tank Cleaning", startingPrice: 300 },
  { title: "Generator Repair", startingPrice: 90 },
  { title: "Lawn Sprinkler Installation", startingPrice: 150 },
  { title: "Smart Doorbell Setup", startingPrice: 60 },
  { title: "Motion Sensor Installation", startingPrice: 70 },
  { title: "Door Closer Fix", startingPrice: 40 },
  { title: "WiFi Router Setup", startingPrice: 30 },
  { title: "Exhaust Fan Installation", startingPrice: 35 },
  { title: "LED Strip Lighting", startingPrice: 50 },
  { title: "Furniture Polishing", startingPrice: 70 },
  { title: "Sump Cleaning", startingPrice: 150 },
  { title: "House Shifting Help", startingPrice: 250 },
  { title: "Iron Grills Fixing", startingPrice: 100 },
  { title: "Railing Welding", startingPrice: 90 },
  { title: "Door Frame Installation", startingPrice: 130 },
  { title: "False Ceiling Light Work", startingPrice: 160 },
  { title: "Wall Partition Setup", startingPrice: 200 },
  { title: "Indoor Plant Setup", startingPrice: 40 },
  { title: "Gas Pipeline Installation", startingPrice: 180 },
  { title: "Shower Panel Fitting", startingPrice: 90 },
  { title: "Sliding Door Fix", startingPrice: 75 },
  { title: "Pet Door Installation", startingPrice: 45 },
  { title: "Gutter Cleaning", startingPrice: 85 },
  { title: "Rainwater Harvesting", startingPrice: 300 },
  { title: "Home Security System Setup", startingPrice: 400 },
  { title: "Driveway Pressure Wash", startingPrice: 110 },
  { title: "Basement Waterproofing", startingPrice: 500 },
  { title: "Attic Insulation", startingPrice: 350 },
  { title: "Wall Socket Fixing", startingPrice: 20 },
  { title: "Ceiling Crack Repair", startingPrice: 75 },
  { title: "Masonry Work", startingPrice: 100 },
  { title: "Wall Paper Installation", startingPrice: 130 },
  { title: "Kitchen Tile Backsplash", startingPrice: 140 },
  { title: "Loft Storage Setup", startingPrice: 200 },
  { title: "Grill Painting", startingPrice: 60 },
  { title: "Gate Automation", startingPrice: 250 },
  { title: "Roof Ventilation Installation", startingPrice: 180 },
  { title: "House Fumigation", startingPrice: 190 },
  { title: "Vinyl Flooring Installation", startingPrice: 220 },
  { title: "Aluminium Partition Setup", startingPrice: 300 },
  { title: "Curtain Cleaning", startingPrice: 40 },
  { title: "Water Softener Installation", startingPrice: 350 },
  { title: "Kitchen Sink Replacement", startingPrice: 100 },
  { title: "Ceiling Tile Replacement", startingPrice: 90 },
  { title: "Under Sink Cabinet Work", startingPrice: 110 },
  { title: "Storage Water Heater Repair", startingPrice: 95 },
  { title: "Bathroom Mirror Mounting", startingPrice: 30 },
  { title: "Glass Door Fixing", startingPrice: 140 },
  { title: "Mosquito Net Fixing", startingPrice: 50 },
  { title: "Decorative Lighting Setup", startingPrice: 150 },
  { title: "Hand Shower Replacement", startingPrice: 25 },
  { title: "Welding Services", startingPrice: 60 },
  { title: "Rain Gutter Installation", startingPrice: 170 }, */
  { title: "General Handyman", startingPrice: 250,     id: 1, },
  { title: "TV Mounting", startingPrice: 80,     id: 2, },
  { title: "Furniture Assembly", startingPrice: 30,     id: 3, },
  { title: "House Cleaning", startingPrice: 60,     id: 4, },
  { title: "Furniture Moving", startingPrice: 20,     id: 5, },
  { title: "Hanging", startingPrice: 15,     id: 6, },
  { title: "Light Fixtures", startingPrice: 40,     id: 7, },
  { title: "Landscaping", startingPrice: 250,     id: 11, },


  
  { title: "Hauling", startingPrice: 20,     id: 8, },
  { title: "Gutter Cleaning", startingPrice: 15,     id: 9, },
  { title: "Holiday Lights", startingPrice: 40,     id: 10, },
  { title: "Smoke Detectors", startingPrice: 250,     id: 12, },
];


export default houseServices;
